ti_core:
    resource: "@TICoreBundle/Resources/config/routing.yml"
    prefix:   /

ti_platform:
    resource: "@TIPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: '@AppBundle/Controller/'
    type: annotation
