# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        TI\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:     [ROLE_AUTHOR, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
             id: fos_user.user_provider.username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: ti_platform_home
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

