ti_platform_home:
    path:     /{page}
    defaults:
        _controller: TIPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

ti_platform_view:
    path:     /advert/{id}
    defaults:
        _controller: TIPlatformBundle:Advert:view
    requirements:
        id: \d+

ti_platform_add:
    path:     /add
    defaults:
        _controller: TIPlatformBundle:Advert:add

ti_platform_edit:
    path:     /edit/{id}
    defaults:
        _controller: TIPlatformBundle:Advert:edit
    requirements:
        id: \d+

ti_platform_delete:
    path:     /delete/{id}
    defaults:
        _controller: TIPlatformBundle:Advert:delete
    requirements:
        id: \d+