services:
#    ti_platform.example:
#        class: TI\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ti_platform.antispam:
        class: TI\PlatformBundle\Antispam\Antispam
        arguments:
            - 50
