<?php

namespace TI\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts($page, $nbPerPage) //With a paginator
    {
    $query = $this->createQueryBuilder('a')
        ->orderBy('a.date', 'DESC')
        ->getQuery();

    $query
        ->setFirstResult(($page-1) * $nbPerPage)
        ->setMaxResults($nbPerPage);

    return new Paginator($query, false);
    }
}
