<?php

namespace TI\PlatformBundle\Repository;

/**
 * WeightCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeightCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
